# Generated by Django 5.0.3 on 2024-03-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0002_remove_flats_aminitie_flat_flat_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat_image',
            name='flat_name',
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('bhk', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('details', models.TextField()),
                ('aminitie', models.ManyToManyField(to='offcampus.aminities')),
            ],
        ),
        migrations.CreateModel(
            name='Flat_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/asset/rooms/flats')),
                ('nearby', models.CharField(max_length=200)),
                ('accommodation', models.CharField(max_length=200)),
                ('flat_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offcampus.flats')),
            ],
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='Flat_Image',
        ),
    ]
