# Generated by Django 5.0.3 on 2024-03-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0003_remove_flat_image_flat_name_flats_flat_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats',
            name='livingroom',
            field=models.ImageField(default=None, upload_to='static/images/asset/rooms/flats'),
        ),
    ]
