# Generated by Django 5.0.3 on 2024-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0004_flats_livingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_images',
            name='km',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
