# Generated by Django 5.0.3 on 2024-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0005_flat_images_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_images',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/asset/rooms/flats'),
        ),
    ]
