# Generated by Django 5.0.3 on 2024-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0006_alter_flat_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Feamle'), ('co-living', 'Co-living')], default=None, max_length=100),
        ),
    ]
