# Generated by Django 5.0.3 on 2024-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0007_flats_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'feamle'), ('Co-living', 'co-living')], default=None, max_length=100),
        ),
    ]
