# Generated by Django 5.0.3 on 2024-03-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0008_alter_flats_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_images',
            name='accommodation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flat_images',
            name='km',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='flat_images',
            name='nearby',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
