# Generated by Django 5.0.3 on 2024-03-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0009_alter_flat_images_accommodation_alter_flat_images_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=200)),
                ('userphone', models.CharField(max_length=10)),
                ('satisfy', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
