# Generated by Django 5.0.3 on 2024-03-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='satisfy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='useremail',
            field=models.EmailField(max_length=254),
        ),
    ]
