# Generated by Django 5.0.3 on 2024-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0011_alter_feedback_satisfy_alter_feedback_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='satisfy',
            field=models.CharField(max_length=10),
        ),
    ]
