# Generated by Django 5.0.3 on 2024-04-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0013_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_cno', models.CharField(max_length=100)),
                ('parent_cno', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('parent_email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('check_in_date', models.CharField(max_length=100)),
                ('check_out_date', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
            ],
        ),
    ]
