# Generated by Django 5.0.3 on 2024-04-12 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0015_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offcampus.city'),
        ),
    ]
