# Generated by Django 5.0.3 on 2024-04-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0016_alter_flats_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
