# Generated by Django 5.0.3 on 2024-04-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0017_alter_flats_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_name', models.CharField(max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('bhk', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('livingroom', models.ImageField(default=None, upload_to='static/images/asset/rooms/flats')),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'feamle'), ('Co-living', 'co-living')], default=None, max_length=100)),
                ('details', models.TextField()),
                ('aminitie', models.ManyToManyField(to='offcampus.aminities')),
            ],
        ),
        migrations.AlterField(
            model_name='flat_images',
            name='flat_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offcampus.flat'),
        ),
        migrations.DeleteModel(
            name='Flats',
        ),
    ]
