# Generated by Django 5.0.3 on 2024-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0018_flat_alter_flat_images_flat_name_delete_flats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='city',
        ),
        migrations.AddField(
            model_name='flat',
            name='cities',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
