# Generated by Django 5.0.3 on 2024-04-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0020_flats_alter_flat_images_flat_name_delete_flat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
