# Generated by Django 5.0.3 on 2024-04-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offcampus', '0021_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('cityimg', models.ImageField(upload_to='static/images/asset')),
            ],
        ),
        migrations.AlterField(
            model_name='flats',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offcampus.city'),
        ),
    ]
